apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.28.1
    name: alertmanager-main
    namespace: monitoring
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.27.0
    name: blackbox-exporter
    namespace: monitoring
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: monitoring
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 12.1.0
    name: grafana
    namespace: monitoring
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.17.0
    name: kube-state-metrics
    namespace: monitoring
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 1.9.1
    name: node-exporter
    namespace: monitoring
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: metrics-adapter
      app.kubernetes.io/name: prometheus-adapter
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.12.0
    name: prometheus-adapter
    namespace: monitoring
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-k8s
    namespace: monitoring
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.85.0
    name: prometheus-operator
    namespace: monitoring
kind: List
metadata: {}
